// Generated by CoffeeScript 1.10.0
(function() {
  var R;

  R = function(options) {
    var _current_path, _previous_path, add, beAMan, check, clearSlashes, flush, getFragment, getPreviousPath, getRoutes, init, navigate, remove, settings, start;
    settings = {
      routes: {},
      modern: false,
      jlo: false,
      root: '/',
      autostart: true
    };
    _current_path = '#';
    _previous_path = window.location.pathname;
    init = function(options) {
      if (history && history.pushState) {
        settings.modern = true;
      }
      if (options) {
        if (options.root) {
          settings.root = '/' + clearSlashes(options.root) + '/';
        }
        if (typeof options.autostart !== 'undefined') {
          settings.autostart = options.autostart;
        }
        if (options.jlo) {
          settings.jlo = options.jlo;
        }
      }
      return this;
    };
    getRoutes = function() {
      return settings.routes;
    };
    getFragment = function() {
      var fragment, match;
      if (settings.modern) {
        fragment = clearSlashes(decodeURI(location.pathname + location.search));
        fragment = fragment.replace(/\?(.*)$/, '');
        if (settings.root !== '/') {
          fragment = fragment.replace(settings.root, '');
        }
      } else {
        match = location.href.match(/#(.*)$/);
        fragment = match ? match[1] : '';
      }
      return clearSlashes(fragment);
    };
    getPreviousPath = function() {
      return _previous_path;
    };
    clearSlashes = function(path) {
      return path.toString().replace(/\/$/, '').replace(/^\//, '');
    };
    add = function(regex, callback) {
      var pattern;
      if (typeof regex === 'function') {
        callback = regex;
        regex = '';
      }
      pattern = clearSlashes(regex);
      settings.routes[pattern] = callback;
      return this;
    };
    remove = function(param) {
      var callback, ref, regex;
      ref = settings.routes;
      for (regex in ref) {
        callback = ref[regex];
        if (callback === param || regex.toString() === param.toString()) {
          settings.routes[regex] = null;
          delete settings.routes[regex];
        }
      }
      return this;
    };
    flush = function() {
      settings.routes = [];
      settings.modern = true;
      settings.root = null;
      return this;
    };
    navigate = function(pth) {
      var hash, path;
      path = pth ? pth.replace(settings.root, '') : '';
      hash = window.location.hash;
      if (settings.modern) {
        history.pushState(path + hash, null, settings.root + clearSlashes(path + hash));
        check();
      } else {
        window.location.hash = path + ':' + hash.replace('#', ':');
      }
      return this;
    };
    check = function(e) {
      var callback, fragment, match, pattern, ref, regex;
      if (settings.jlo) {
        beAMan();
        return false;
      }
      fragment = getFragment();
      if (_current_path === fragment) {
        return false;
      }
      ref = settings.routes;
      for (pattern in ref) {
        callback = ref[pattern];
        regex = new RegExp(pattern);
        match = fragment.match(regex);
        if (match) {
          _current_path = fragment;
          callback.apply({}, match);
          _previous_path = _current_path;
        }
      }
      return this;
    };
    beAMan = function() {
      return window.open('http://qph.is.quoracdn.net/main-thumb-2536154-200-NnwoJwWfCGkQyMdFd9CBF71iZsPQnKyZ.jpeg', 'J-Lo', 'height=200,width=200');
    };
    start = function() {
      window.addEventListener('popstate', check);
      if (settings.autostart) {
        return navigate(window.location.pathname);
      }
    };
    init(options);
    return {
      add: add,
      remove: remove,
      flush: flush,
      navigate: navigate,
      start: start,
      routes: getRoutes,
      previousPath: getPreviousPath
    };
  };

  window.Router = function(options) {
    return new R(options);
  };

}).call(this);
